#!/usr/bin/env ruby --disable-gems

require "digest"

range = 0..255
seed = Digest::SHA256.hexdigest(Dir.pwd).hex
generator = Random.new(seed)

# https://iterm2.com/documentation-escape-codes.html
print "\033]6;1;bg;red;brightness;#{generator.rand(range)}\a",
      "\033]6;1;bg;green;brightness;#{generator.rand(range)}\a",
      "\033]6;1;bg;blue;brightness;#{generator.rand(range)}\a"
